id k1.k1 * Sector(topoB) = +1*Den(1)*Sector(topoB)*DD6+Num(m2)*Den(1)*Sector(topoB)*1;
id k1.k2 * Sector(topoB) = +1*Den(2)*Sector(topoB)*DD6+1*Den(2)*Sector(topoB)*DD7+(-1)*Den(2)*Sector(topoB)*DD8+Num(m2)*Den(1)*Sector(topoB)*1;
id k1.p1 * Sector(topoB) = +1*Den(2)*Sector(topoB)*DD6+(-1)*Den(2)*Sector(topoB)*DD9+Num(pp)*Den(2)*Sector(topoB)*1;
id k2.k2 * Sector(topoB) = +1*Den(1)*Sector(topoB)*DD7+Num(m2)*Den(1)*Sector(topoB)*1;
id k2.p1 * Sector(topoB) = +1*Den(2)*Sector(topoB)*DD7+(-1)*Den(2)*Sector(topoB)*DD10+Num(pp)*Den(2)*Sector(topoB)*1;
